service: serverless-guru

provider:
  name: aws
  runtime: nodejs20.x
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    installPath: .dynamodb
    stages:
      - dev
      - local

resources:
  - ${file(iac/dynamodb-tables.yml)}

functions:
- ${file(./src/jobs/application/handlers/functions.yml)}
