service: serverless-guru

provider:
  name: aws
  runtime: nodejs20.x
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  # - serverless-dynamodb-local

functions:
- ${file(./src/jobs/infra/handlers/functions.yml)}
