service: serverless-guru

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/JobTable-${self:provider.stage}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    installPath: .dynamodb
    stages:
      - dev
      - local
  serverless-offline:
    port: 3003
    httpPort: 3004

resources:
  - ${file(iac/dynamodb-tables.yml)}

functions:
- ${file(./src/jobs/application/handlers/functions.yml)}
