list:
  handler: src/jobs/application/handlers/index.list
  events:
    - http:
        path: /jobs
        method: get
getJob:
  handler: src/jobs/application/handlers/index.getJob
  events:
    - http:
        path: /jobs/{id}
        method: get
create:
 handler: src/jobs/application/handlers/index.create
 events:
   - http:
       path: /jobs
       method: post
updateJob:
    handler: src/jobs/application/handlers/index.updateJob
    events:
      - http:
            path: /jobs/{id}
            method: put
delete:
  handler: src/jobs/application/handlers/index.deleteJob
  events:
    - http:
        path: /jobs/{id}
        method: delete
