- name: list
  handler: src/jobs/application/handlers/index.list
  events:
    - http:
        path: /jobs
        method: get

- name: getJob
  handler: src/jobs/application/handlers/index.getJob
  events:
    - http:
        path: /jobs/{id}
        method: get

- name: create
  handler: src/jobs/application/handlers/index.create
  events:
    - http:
        path: /jobs
        method: post

- name: update
  handler: src/jobs/application/handlers/index.updateJob
  events:
    - http:
        path: /jobs/{id}
        method: put

- name: delete
  handler: src/jobs/application/handlers/index.deleteJob
  events:
    - http:
        path: /jobs/{id}
        method: delete
